import { lazy } from "react";
import { Category, Tools } from "@/types/tools";
import type { ToolDef } from "@/types/tools";

export const tools: ToolDef[] = [
  {
    slug: Tools.Base64,
    title: "Base64 Decoder",
    component: lazy(() => import("@/pages/base64")),
    description: "Decode Base64 encoded strings quickly and easily in your browser.",
    icon: "carbon:data-base",
    category: Category.Encoding,
  },
  {
    slug: Tools.Base64Encode,
    title: "Base64 Encoder",
    component: lazy(() => import("@/pages/base64-encode")),
    description: "Encode strings to Base64 format quickly and easily in your browser.",
    icon: "carbon:data-base-alt",
    category: Category.Encoding,
  },
  {
    slug: Tools.JWT,
    title: "JWT Decoder / Encoder",
    component: lazy(() => import("@/pages/jwt")),
    description: "Decode, inspect, and encode JSON Web Tokens (JWT) to view their header, payload, and signature.",
    icon: "carbon:security",
    category: Category.Security,
  },
  {
    slug: Tools.Color,
    title: "Color Converter",
    component: lazy(() => import("@/pages/color")),
    description: "Convert colors between different formats (HEX, RGB, HSL, etc.) with a live preview.",
    icon: "carbon:color-palette",
    category: Category.CSS,
  },
  {
    slug: Tools.ColorCompare,
    title: "Color Compare",
    component: lazy(() => import("@/pages/color-compare")),
    description: "Compare two colors side by side with live swatches and normalized output.",
    icon: "carbon:color-switch",
    category: Category.CSS,
  },
  {
    slug: Tools.Hmac,
    title: "HMAC Generator",
    component: lazy(() => import("@/pages/hmac")),
    description: "Generate a Hash-based Message Authentication Code (HMAC) to verify message integrity and authenticity using your secret key.",
    icon: "carbon:fingerprint-recognition",
    category: Category.Security,
  },
  {
    slug: Tools.Secrets,
    title: "Secret Generator",
    component: lazy(() => import("@/pages/secrets")),
    description: "Generate cryptographically secure secrets and passwords with configurable length and special characters.",
    icon: "carbon:password",
    category: Category.Security,
  },
  {
    slug: Tools.Diff,
    title: "Text Diff",
    component: lazy(() => import("@/pages/diff")),
    description: "Compare two texts and see their differences highlighted, with support for character, word, and line-based diffing.",
    icon: "carbon:compare",
    category: Category.Text,
  },
  {
    slug: Tools.WordCounter,
    title: "Word Counter",
    component: lazy(() => import("@/pages/word-counter")),
    description: "Count characters, words, sentences, and paragraphs in your text with real-time statistics.",
    icon: "carbon:text-annotation-toggle",
    category: Category.Text,
  },
  {
    slug: Tools.SqlFormatter,
    title: "SQL Formatter",
    component: lazy(() => import("@/pages/sql-formatter")),
    description: "Format and beautify SQL queries with syntax highlighting.",
    icon: "carbon:data-base",
    category: Category.Dev,
  },
  {
    slug: Tools.JsonFormatter,
    title: "JSON Formatter",
    component: lazy(() => import("@/pages/json-formatter")),
    description: "Format and prettify your JSON data instantly in your browser.",
    icon: "mdi:code-json",
    category: Category.Dev,
  },
  {
    slug: Tools.QrCode,
    title: "QR Code Generator",
    component: lazy(() => import("@/pages/qr-code")),
    description: "Generate QR codes from text, URLs, or any data directly in your browser.",
    icon: "carbon:qr-code",
    category: Category.Dev,
  },
  {
    slug: Tools.NotificationTester,
    title: "Notification Tester",
    component: lazy(() => import("@/pages/notification-tester")),
    description: "Test browser notifications with permission handling and delayed notifications.",
    icon: "carbon:notification",
    category: Category.Dev,
  },
  {
    slug: Tools.SecretSharing,
    title: "Secret Sharing",
    component: lazy(() => import("@/pages/secret-sharing")),
    description: "Encrypt a secret with a password and share it via a URL. Decrypts in the browser.",
    icon: "carbon:locked",
    category: Category.Security,
  },
  {
    slug: Tools.DnsRecords,
    title: "DNS Records",
    component: lazy(() => import("@/pages/dns-records")),
    description: "Look up DNS records for any domain using Google's public DNS service.",
    icon: "carbon:dns-services",
    category: Category.Dev,
  },
  {
    slug: Tools.TimezoneConverter,
    title: "Timezone Converter",
    component: lazy(() => import("@/pages/timezone-converter")),
    description: "Convert times between different timezones. Supports timestamps, ISO dates, and custom formats.",
    icon: "carbon:time",
    category: Category.Dev,
  },
  {
    slug: Tools.IndiaIncomeTax,
    title: "Income Tax Calculator",
    component: lazy(() => import("@/pages/india-income-tax")),
    description: "Calculate income tax for India's new tax regime (FY 2025-26) with detailed breakdown by slab, cess, and surcharge.",
    icon: "carbon:document",
    category: Category.Finance,
  },
  {
    slug: Tools.BountyCalculator,
    title: "Bounty Calculator",
    component: lazy(() => import("@/pages/bounty-calculator")),
    description: "Suggest a bug bounty payout from a CVSS vector string using tier-based interpolation and component kickers.",
    icon: "carbon:money",
    category: Category.Security,
  },
  {
    slug: Tools.CvssCalculator,
    title: "CVSS Calculator",
    component: lazy(() => import("@/pages/cvss-calculator")),
    description: "Build a CVSS v3.1 vector by picking each metric, see the live base score and severity, and copy or share the result.",
    icon: "carbon:security",
    category: Category.Security,
  },
  {
    slug: Tools.MarkdownViewer,
    title: "Markdown Viewer",
    component: lazy(() => import("@/pages/markdown-viewer")),
    description: "Preview markdown with live rendering, syntax highlighting, and standard GitHub-flavored Markdown support.",
    icon: "carbon:logo-github",
    category: Category.Dev,
  },
  {
    slug: Tools.Whiteboard,
    title: "Whiteboard",
    component: lazy(() => import("@/pages/whiteboard")),
    description: "A virtual whiteboard for sketching hand-drawn like diagrams.",
    icon: "carbon:draw",
    category: Category.Dev,
  },
  {
    slug: Tools.UrlEncoder,
    title: "URL Encoder / Decoder",
    component: lazy(() => import("@/pages/url-encoder")),
    description: "Quickly encode or decode URI components and query parameters.",
    icon: "carbon:link",
    category: Category.Encoding,
  },
  {
    slug: Tools.CronGenerator,
    title: "Cron Expression Generator",
    component: lazy(() => import("@/pages/cron-generator")),
    description: "Visually build, decode, and explain Cron schedules in plain English.",
    icon: "carbon:time",
    category: Category.Dev,
  },
  {
    slug: Tools.RestClient,
    title: "HTTP / REST Client",
    component: lazy(() => import("@/pages/rest-client")),
    description: "A lightweight, in-browser fetch tester for endpoints.",
    icon: "carbon:api",
    category: Category.Dev,
  }
];
